-------------------------------
-- CakeScript Generation 2
-- Author: LuaBanana ( Aka Jake )
-- Project Start: 5/24/2008
--
-- admin_cc.lua
-- Admin commands. Admin functions are in admin.lua
-------------------------------