resource.AddFile( "models/Gustavio/alyxanimtree.mdl" )
resource.AddFile( "models/Gustavio/combineanimtree.mdl" )
resource.AddFile( "models/Gustavio/maleanimtree.mdl" )
resource.AddFile( "models/Gustavio/femaleanimtree.mdl" )
resource.AddFile( "models/Gustavio/metroanimtree.mdl" )
resource.AddFile( "models/Gustavio/barneyanimtree.mdl" )
resource.AddFile( "resource/fonts/Benegraphic.ttf" )
/*
resource.AddFile( "resource/fonts/Base 02.ttf" )
resource.AddFile( "materials/hl2rp/combinearmbandignis.vtf" )
resource.AddFile( "materials/hl2rp/combinearmbandvice.vtf" )
resource.AddFile( "materials/hl2rp/combinearmbandshield.vtf" )
resource.AddFile( "materials/hl2rp/combinearmbandlegion.vtf" )
resource.AddFile( "materials/hl2rp/combinearmbandviktor.vtf" )
resource.AddFile( "materials/hl2rp/overwatch.vtf" )
resource.AddFile( "materials/hl2rp/secbadge.vtf" )
resource.AddFile( "materials/hl2rp/combinearmbandrecruit.vtf" )
resource.AddFile( "materials/hl2rp/lambda.vtf" )
resource.AddFile( "materials/hl2rp/cwu.vtf" )*/