resource.AddFile( "models/Gustavio/alyxanimtree.mdl" )
resource.AddFile( "models/Gustavio/combineanimtree.mdl" )
resource.AddFile( "models/Gustavio/maleanimtree.mdl" )
resource.AddFile( "models/Gustavio/femaleanimtree.mdl" )
resource.AddFile( "models/Gustavio/metroanimtree.mdl" )
resource.AddFile( "models/Gustavio/barneyanimtree.mdl" )
resource.AddFile( "resource/fonts/Benegraphic.ttf" )
resource.AddFile( "resource/fonts/Base 02.ttf" )
resource.AddFile( "materials/rlrp/policeshield.vtf" )
resource.AddFile( "materials/rlrp/melonmafia.vtf" )
resource.AddFile( "materials/rlrp/workersyndicate.vtf" )
